### ISSUE TITLE
Issue with new OCID account creation

### ISSUE THREAD

**Issue by AlineMADCourses** [opencampus-xyz/ocid-connect-js#28]
**Environment**

- SDK Version: [e.g., v1.2.3]  - not sure how to find this
- Operating System: Windows 10
- Browser: Chrome

**Expected Behavior**

The login through OCID connect for new accounts should redirect us to our Landing Page - using this link https://mad-platform.vercel.app/login  

**Actual Behavior**

It stays stuck on the OCID connect final stage

**Error Message and Stack Trace**

see video here: https://www.loom.com/share/95e3ca983117490f9d40c6a204662be4?sid=ccd05805-8aad-4cf6-8a18-445e15a43dc5 

**Additional Context**
We have been having issues with the OCID connect the past days (never before):

1st issue : impossible to access connect through OCID for both new and existing accounts with the following message : Unprocessable Entity - the referral code cannot be updated once created
It solved itself on its own 

But then a few hours later existing accounts could have access BUT we could not create new accounts (the issue that I am reporting here)

**Comment by joshkyleclemente** [comment]
same issue with my project for new created accounts to OCID Connect error encountered after finish fill up registration form we cant enter the dashboard

It still stuck on the OCID connect final stage

**Comment by jackyquang** [comment]
Thanks, we are looking into this.

**Comment by jackyquang** [comment]
@joshkyleclemente @AlineMADCourses the issue is fixed. Thanks for spotting this.

**Comment by AlineMADCourses** [comment]
Hello, we are still experiencing issues with this
I'm opening a new issue to upload some screenshots
